<div class="footer-menu-links">

    <div class="links">
        <div class="block-title"><strong><span><?php echo $this->__('MIGLIORI') ?></span></strong></div>
        <ul>
            <li><a href="<?php echo $this->getUrl('')?>"><?php echo $this->__('Our shoes') ?></a></li>
            <li><a href="<?php echo $this->getUrl('')?>"><?php echo $this->__('OUR SERVICES') ?></a></li>
            <li><a href="<?php echo $this->getUrl('')?>"><?php echo $this->__('ABOUT COMPANY') ?></a></li>
        </ul>
    </div>

    <div class="links">
        <div class="block-title"><strong><span><?php echo $this->__('OUR SERVICES') ?></span></strong></div>
        <ul>
            <li><a href="<?php echo $this->getUrl('')?>"><?php echo $this->__('RESTORATION') ?></a></li>
            <li><a href="<?php echo $this->getUrl('')?>"><?php echo $this->__('TO MEASURE') ?></a></li>
            <li><a href="<?php echo $this->getUrl('')?>"><?php echo $this->__('SELECTION') ?></a></li>
        </ul>
    </div>

    <div class="links">
        <div class="block-title"><strong><span><?php echo $this->__('USERS') ?></span></strong></div>
        <ul>
            <li><a href="<?php echo $this->getUrl('')?>"><?php echo $this->__('CONTACT US') ?></a></li>
            <li><a href="<?php echo $this->getUrl('')?>"><?php echo $this->__('WORKING CONDITIONS') ?></a></li>
            <li><a href="<?php echo $this->getUrl('')?>"><?php echo $this->__('WRITE TO THE DIRECTOR') ?></a></li>
        </ul>
    </div>

    <div class="links">
        <div class="block-title"><strong><span><?php echo $this->__('HELP') ?></span></strong></div>
        <ul>
            <li><a href="<?php echo $this->getUrl('')?>"><?php echo $this->__('REVIEWS') ?></a></li>
            <li><a href="<?php echo $this->getUrl('')?>"><?php echo $this->__('FREQUENTLY ASKED QUESTIONS') ?></a></li>
            <li><a href="<?php echo $this->getUrl('')?>"><?php echo $this->__('Delivery of articles') ?></a></li>
        </ul>
    </div>

</div>

