<nav id="nav">
    <ol class="nav-primary">
        <li class="level0 nav-1 parent"><a href="" title="Home" class="level0"><?php echo $this->__("Home") ?></a></li>
        <li class="level0 nav-1 parent"><a href="shop" title="Shop" class="level0"><?php echo $this->__("Shop") ?></a></li>
        <li class="level0 nav-1 parent"><a href="guide-shop" title="Guide shop" class="level0"><?php echo $this->__("Guide shop") ?></a></li>
        <li class="level0 nav-1 parent"><a href="made-to-order" title="Made to order" class="level0"><?php echo $this->__("Made to order") ?></a></li>
        <li class="level0 nav-1 parent"><a href="about-magento-demo-store" title="About Us" class="level0"><?php echo $this->__("About Us") ?></a></li>
        <li class="level0 nav-1 parent"><a href="customer-service" title="Services" class="level0"><?php echo $this->__("Services") ?></a></li>
        <li class="level0 nav-1 parent"><a href="contact" title="Contacts" class="level0"><?php echo $this->__("Contacts") ?></a></li>
    </ol>
</nav>
